sphereio/sphere-node-sdk

src/coffee/main.coffee
src/coffee/sync/category-sync.coffee
src/coffee/sync/utils/category-utils.coffee
src/coffee/sync/utils/category.coffee
src/spec/exports.spec.coffee
src/spec/sync/category-sync.spec.coffee
src/spec/sync/utils/category-utils.spec.coffee

With this PR we are able to update categories to any supported update action - currently there are 6 actions.
@butenkor and @emmenko  please review.

Category sync

---

src/coffee/services/base.coffee
src/spec/client/client.spec.coffee
src/spec/client/services/product-projections.spec.coffee

Warn if response has a deprecation header. Closes #56

---

src/coffee/client.coffee
src/coffee/errors.coffee
src/spec/errors.spec.coffee

@emmenko please review. Refs #71

Status code

---

src/coffee/services/customers.coffee
src/spec/integration/customers.spec.coffee

Support login function for customers.

---

src/coffee/sync/product-sync.coffee
src/coffee/sync/utils/product.coffee
src/spec/connect/rest.spec.coffee

Add: categories actions map

---

src/coffee/connect/oauth2.coffee
src/coffee/connect/rest.coffee
src/spec/connect/oauth2.spec.coffee
src/spec/connect/rest.spec.coffee

client ID and secret are not necessary when the oauth token is given
@emmenko please review

can configure base urls, not only hosts

---

src/coffee/client.coffee
src/coffee/errors.coffee
src/coffee/services/base.coffee
src/coffee/services/graphql.coffee
src/spec/client/client.spec.coffee
src/spec/client/services/graphql.spec.coffee
src/spec/errors.spec.coffee
src/spec/integration/graphql.spec.coffee
src/spec/integration/products.spec.coffee

Basic support of graphql endpoint

---

src/coffee/sync/utils/product.coffee

fix(productDiff): diff variants by sku or id

---

src/coffee/services/base.coffee
src/spec/client/services/base.spec.coffee

feat(response): add url and timeout information to original request

---

src/coffee/client.coffee
src/coffee/services/base.coffee
src/coffee/utils.coffee
src/spec/client/services/base.spec.coffee

closes #109 
@emmenko @butenkor

feat(baseService): add secure option to filter for http authorization header

---

src/coffee/sync/utils/product.coffee
src/spec/integration/products-sync.spec.coffee
src/spec/sync/utils/product.spec.coffee

closes #114 
@emmenko please review

fix(productSync): prevent actions that would remove images from CDN unwantedly

---

src/coffee/services/orders.coffee

feat(orders): add support for deletion of orders

---

src/coffee/services/base.coffee
src/coffee/services/cart-discounts.coffee
src/coffee/services/carts.coffee
src/coffee/services/categories.coffee
src/coffee/services/channels.coffee
src/coffee/services/custom-objects.coffee
src/coffee/services/customer-groups.coffee
src/coffee/services/customers.coffee
src/coffee/services/discount-codes.coffee
src/coffee/services/graphql.coffee
src/coffee/services/inventory-entries.coffee
src/coffee/services/messages.coffee
src/coffee/services/orders.coffee
src/coffee/services/payments.coffee
src/coffee/services/product-discounts.coffee
src/coffee/services/product-projections.coffee
src/coffee/services/product-types.coffee
src/coffee/services/products.coffee
src/coffee/services/project.coffee
src/coffee/services/reviews.coffee
src/coffee/services/shipping-methods.coffee
src/coffee/services/states.coffee
src/coffee/services/tax-categories.coffee
src/coffee/services/types.coffee
src/coffee/services/zones.coffee
src/spec/client/services/base.spec.coffee

closes #102 #123 
cc @emmenko @yanns

feat(base-service): add support for fetching by key to product type and type service

---

src/coffee/connect/rest.coffee
src/spec/connect/rest.spec.coffee

feat(auth): automatically renew an access_token before it expires

---

lib/sync/product-actions.js
test/sync/product-sync-variants.spec.js

[v2] fix(product-sync): migrate deprecated set sku action

---

src/coffee/services/base.coffee
src/spec/client/services/base.spec.coffee
src/spec/integration/products.spec.coffee

feat(request): support ref expansion on post requests. Fixes #145

---

lib/sync/category-actions.js
lib/sync/inventories.js
lib/sync/inventory-actions.js
lib/sync/utils/common-actions.js
test/index.js
test/sync/inventory-sync.spec.js

feat(sync): add sync actions for inventory

---

src/coffee/services/base.coffee
src/spec/client/services/base.spec.coffee
src/spec/client/services/product-projections.spec.coffee

make process function more robust to work with given query string

---

src/coffee/sync/utils/product.coffee
src/spec/sync/product-sync.spec.coffee

fix(product-import): allow import of masterVariant

---

src/coffee/sync/product-sync.coffee
src/spec/sync/product-sync.spec.coffee

Fixes: https://github.com/sphereio/sphere-node-sdk/issues/130

#130 Product sync should sort update actions

---

package.json
src/coffee/sync/inventory-sync.coffee
src/coffee/sync/utils/inventory.coffee
src/spec/integration/inventories-sync.spec.coffee
src/spec/sync/inventory-sync.spec.coffee
src/spec/sync/product-sync.spec.coffee

Add custom field

---

src/spec/integration/products-sync.spec.coffee
src/spec/sync/product-sync.spec.coffee

Test price custom type and field handling

---

src/coffee/sync/inventory-sync.coffee
src/coffee/sync/utils/inventory.coffee
src/spec/sync/inventory-sync.spec.coffee

Fix setting a new custom type and fields on an existing inventory entry.
Closes #182

fix(inventory): fix new custom type and fields importing

---

src/coffee/sync/order-sync.coffee
src/coffee/sync/utils/order.coffee
src/spec/integration/orders-sync.spec.coffee
src/spec/sync/utils/order.spec.coffee

Support order custom line items

---

package.json
src/coffee/client.coffee
src/coffee/connect/oauth2.coffee
src/coffee/repeater-task-queue.coffee
src/spec/client/client.spec.coffee
src/spec/connect/oauth2.spec.coffee
src/spec/integration/inventories-sync.spec.coffee
src/spec/integration/orders-sync.spec.coffee
src/spec/integration/products-sync.spec.coffee
src/spec/integration/products.spec.coffee
src/spec/repeater-task-queue.spec.coffee

Add default task repeater

---

docs/INDEX.md

Fix getting-started link

---

src/coffee/repeater-task-queue.coffee

fixes #201 sphereio/sphere-product-import#91

fix(repeater-task-queue): rewrite es6 specific code

---

package.json

This has been discussed with @Siilwyn

chore(package.json): move underscore-mixins to devDependencies

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

docs(contributing.md): update contributing guildelines

---

src/coffee/client.coffee
src/coffee/connect/rest.coffee
src/spec/connect/rest.spec.coffee
src/spec/integration/gzip.spec.coffee
src/spec/integration/products.spec.coffee

feat(gzip): allow gzip by default for all requests

---

CONTRIBUTING.md

docs(contributing): Add info about MQ variables

---

package.json
src/spec/integration/discounts.spec.coffee

Bump dependencies whose older versions contain vulnerabilities

fix(dependencies): Bump dependencies

---

src/coffee/sync/utils/product.coffee
src/spec/sync/product-sync.spec.coffee
src/spec/sync/utils/product.spec.coffee

feat(sync): utilise priceId for update

---

.travis.yml
README.md
package.json

build(node): drop support for node versions below 6

---

package.json
src/spec/integration/gzip.spec.coffee

Updates `request` dependancy to solves confusing error problem.
closes #258

chore(deps): update request dep

---

src/coffee/repeater-task-queue.coffee
src/spec/repeater-task-queue.spec.coffee

Add more error keywords to repeat on

---

package-lock.json
src/coffee/sync/inventory-sync.coffee
src/coffee/sync/utils/inventory.coffee
src/spec/integration/inventories-sync.spec.coffee
src/spec/sync/inventory-sync.spec.coffee

Add support for RestockableInDays
This support the use and modification (addition, updating and removal) of `restockableInDays`.
- Tests
closes #274

feat(inventories-sync): add support for restockable in days

---

src/coffee/sync/product-sync.coffee
src/coffee/sync/utils/product.coffee
src/spec/sync/utils/product.spec.coffee

Fixes https://github.com/sphereio/sphere-node-sdk/issues/327

feat(product): add option to match by only one attr (#327)

---

src/coffee/sync/utils/product.coffee
src/spec/sync/utils/product.spec.coffee

fix(product-sync): findVariantInList when attributeToMatchBy used.
