sphereio/sphere-node-sdk

src/coffee/services/product-projections.coffee
src/spec/client/services/product-projections.spec.coffee

Allow to process search results. Refs #75.

---

src/coffee/services/base.coffee
src/coffee/services/product-projections.coffee
src/spec/client/services/product-projections.spec.coffee

With this PR, we store each parameter from the querystring which is necessary if we use the process function for batch processing.
I used an explicit array for the plain attributes that don't need encoding.
@emmenko please review.
BTW: I don't know why only one search suggest job is failing in travis: https://travis-ci.org/sphereio/sphere-node-sdk/jobs/84246626

Querystring

---

src/coffee/sync/utils/product.coffee
src/spec/integration/products-sync.spec.coffee
src/spec/integration/products.spec.coffee
src/spec/sync/product-sync.spec.coffee
src/spec/sync/utils/product.spec.coffee

Hi,
I added setSearchKeywords update action to the Product Sync.
Plz review @emmenko @hajoeichler 
thanks
for some reason this test fails though- although absolutely nothing has changed in that function - so it must have been an existing issue which looks more backend related:
```
1) Integration Products should search for suggestions
Message:
Expected [  ] to equal [ { text : 'Schweizer Messer' } ].
```

WIP  added searchKeywords update action

---

src/coffee/services/base.coffee
src/spec/client/services/base.spec.coffee

Since the API was changed, so that limit=0 won't return any results
closes #106 
@emmenko @mmoelli

fix(baseService): use limit of 20 if limit is 0

---

package.json

With these changes I am able to run all npm scripts on windows.
- I replaced all commands which are not available under windows with cross-platform substitutions.
- Replaced `tape-run` with `smokestack` because tape-run was not able to detect browsers on windows.

Add windows support for npm scripts (cross-platform)

---

src/coffee/services/base.coffee
src/spec/client/services/base.spec.coffee

The status code 500 was also shown if there was no response from the server (timeout), which was
confusing since getting a status code looks like there was a response from the server.
closes #113 
/cc @emmenko

refactor(baseService): remove standard status code of 500

---

src/coffee/connect/rest.coffee
src/spec/connect/rest.spec.coffee

so that it is possible to for example expand multiple references
fixes #117

fix(pagedRequest): set hasUniqueParams option to false

---

lib/sync/categories.js
lib/sync/category-actions.js
lib/sync/product-actions.js
lib/sync/utils/actions-utils.js
test/index.js
test/sync/category-sync.spec.js

- add category sync lib
- add action creators for all category actions support by the API
- refactored `_buildBaseAttributesAction` into `actions-utils.js`, since it may be used by multiple sync libs
- add unit tests for all possible category sync actions
cc/ @hajoeichler @emmenko @ct-dali

feat(categorySync): add support for syncing categories

---

src/coffee/connect/rest.coffee
src/spec/connect/rest.spec.coffee

Now you are able to provide your own sorting when doing `all()`. If you don't provide any sorting it
will still sort by id by default.
closes #122
cc @emmenko

refactor(rest): prevent overwriting of sort when using all()

---

src/coffee/services/base.coffee
src/spec/client/services/base.spec.coffee
src/spec/client/services/product-projections.spec.coffee

Now the all() method no longer calls perPage(0) and thus set the limit=0. This is legacy since it
was used in the past to fetch all entries from a CTP API endpoint. Now doing limit=0 is used to get
the base stats without getting any results and all() is (still) beeing used to get all results from
an CTP API endpoint.
cc @emmenko

refactor(fetch): perPage(0) which corresponds to limit=0 no longer triggers a page request.

---

src/coffee/errors.coffee
src/coffee/services/base.coffee
src/coffee/sync/utils/product.coffee
src/spec/client/services/base.spec.coffee
src/spec/errors.spec.coffee
src/spec/integration/products-sync.spec.coffee
src/spec/sync/product-sync.spec.coffee
src/spec/sync/utils/product.spec.coffee

- check if `byId` or `byKey` were used before calling `delete`. This previously would lead to a program error in the SDK, which is also fixed now with this PR 4d2f4b3
- handle 405 errors and show descriptive error message, since the CTP API does not provide one
- fix handling of graphql 400 errors. Previously these would not occur with status code 400. Since the now do this update was needed. abae23c
- add support for generating update actions for product transitions
- add unit and integration tests for product state transition actions
cc/ @emmenko @hajoeichler @butenkor

Add support for generating update actions for product state transitions

---

src/coffee/sync/utils/product.coffee
src/spec/sync/utils/product.spec.coffee

Since the API throws an error when you try to set the state to null, there is no sence in letting
the user run into this. It is a common use case that the state is not known and not important to
some importing service.
#137
cc @butenkor

Don't generate update actions when no state is provided

---

lib/sync/product-actions.js
test/sync/product-sync-variants.spec.js

This is a bug that was noticed in the MC. At the moment when you unset the SKU of an existing variant (that has an SKU set), there is no update action generated.
This is now changed, so that the only case where no update action is generated is when the old and the new draft have no SKU set (or an empty SKU)

fix(product-sync): allow unsetting of sku if one was set

---

src/coffee/sync/utils/product.coffee
src/spec/sync/utils/product.spec.coffee

- ~~code is integration tested~~
- ~~public code is documented~~

fix(product-sync): fix setting multiple category order hints at once

---

src/coffee/sync/utils/product.coffee
src/spec/sync/product-sync.spec.coffee
src/spec/sync/utils/product.spec.coffee

- ~~code is integration tested~~
- ~~public code is documented~~

fix(product-sync): stringify order hint values

---

package.json
src/sync/product-actions.js
test/sync/product-sync-variants.spec.js

Fix a problem for product update actions where duplicate SFA attributes were generated.
If multiple variants have the same SFA attribute, and this somehow changed (added, removed, changed), multiple equal actions were generated.
The problem was that the wrong lodash function was used, which allows to filter out from an array non-unique items.
- Tests

fix(product-actions): use correct uniq function to ensure unique sfa attributes

---

src/sync/customer-actions.js
test/sync/customer-sync.spec.js

This PR adds generation of customer default shipping / billing address actions

Customer Default Address Actions

---

src/sync/product-actions.js
src/sync/utils/diffpatcher.js
test/sync/product-sync-base.spec.js
test/sync/product-sync-variants.spec.js

Product actions for variant attributes `ltext` were failing because of missing original object in case of long text diff.
- Tests

fix(product-actions): correctly pass original obj for patching long text diff

---

src/coffee/sync/inventory-sync.coffee
src/coffee/sync/utils/inventory.coffee
src/spec/sync/inventory-sync.spec.coffee

When a custom field already exists use the new object value. This solves the [breaking build](https://travis-ci.org/sphereio/sphere-stock-import/builds/178220591) in stock import. I introduced this bug when just using `diff` in 79e3475aae2569056ebe688938d46d38e8b1a8fc. 🤕

Fix updating existing custom fields

---

package.json

The released code is using the lib, so an exception is raised whenever the compiled code is used from a fresh npm install. This was introduced in [this commit](https://github.com/sphereio/sphere-node-sdk/commit/2ca67014297aee4b77118b8f0b25aa575992d978) and the dependency was added to devDependecies [here](https://github.com/sphereio/sphere-node-sdk/commit/4227cfee0aeb17f2192ac3a3ffd9e1b1679541f8) to fix the test.

Move sphere-node-utils dependency to dependencies

---

.travis.yml
package.json

By adding the missing  dependency we depend on a specific version in the CI environment.
And we don't assume it's globally installed in a development environment.

chore(dependencies): add missing grunt-cli dependency

---

src/coffee/services/inventory-entries.coffee
src/coffee/sync/inventory-sync.coffee
src/coffee/sync/utils/inventory.coffee
src/spec/errors.spec.coffee
src/spec/sync/inventory-sync.spec.coffee
src/spec/sync/utils/inventory.spec.coffee

The main reason for this change is it's easier to repeat the request in case of concurrent modification error. With the old diff calculation, it's necessary to refetch the inventories and recalculate the diff. With this new change, it's enough to change the version number and repeat the request.

fix(inventory): change quantity instead of calculating the difference

---

src/coffee/sync/product-sync.coffee
src/spec/sync/product-sync.spec.coffee

Product sync updates needs to set attributes before adding new variants. The problem is when you have setAttributeInAllVariants for same for all attribute and a new variant, you need to change the same for all value for old variants first before you can create the new variant.

fix(product-sync): set attributes before add variants

---

src/coffee/sync/utils/product.coffee
src/spec/sync/utils/product.spec.coffee

When the new product attribute contains same elements as the old product attribute, but only in different order, the update action is created and sent to the API. However, since nothing was changed, an error is returned from the API:
BadRequest: A duplicate combination of the variant values (sku, key, images, prices, attributes) exists.
Solution: check if the product attribute has really changed or the elements of the attribute are just in a different order.

fix(product): dont create setAttribute action when the product attribute did not change

---

src/coffee/sync/utils/product.coffee
src/spec/sync/utils/product.spec.coffee

The old code deleted the attribute of an object that was part of the original product attribute. So instead of correct format:
```js
{ name: 'attributeName', value: 'attributeValue' }
```
we had:
```js
{ name: 'attributeName' }
```
in the variant attributes of the original product. I fixed it by replacing the old code with the one from the new node SDK.
https://github.com/commercetools/nodejs/blob/ab8edfb41bdc7d429f20554d3d8a45ef251228f8/packages/sync-actions/src/product-actions.js#L286

fix(product): don't modify original product when building variant attributes

---

src/coffee/sync/utils/product.coffee
src/spec/sync/utils/product.spec.coffee

fix(ProductSync): Fix checking of an attribute difference - Issue #209

---

src/coffee/sync/product-sync.coffee
src/coffee/sync/utils/product.coffee
src/spec/sync/product-sync.spec.coffee
src/spec/sync/utils/product.spec.coffee

This PR fixes #218 
When generating product update actions category actions should be placed before categoryOrderHint actions so we can add product to category and create a categoryOrderHint in one request.
- Tests

fix(productSync): Update categories before categoryOrderHints

---

src/coffee/sync/order-sync.coffee
src/coffee/sync/utils/order.coffee
src/spec/sync/order-sync.spec.coffee
src/spec/sync/utils/order.spec.coffee
src/spec/utils.spec.coffee

Fixes #229 
When adding a new parcel to a delivery, the script goes through all deliveries to find proper `deliveryId`. It also ignores all diffs items starting with an underscore `_` because those items were removed and we do not currently support removed deliveries/parcels.
This PR also improves code coverage:
> Here I discovered that the `deliveryId` has to be always present when adding new parcel because if it is missing, the script will add whole delivery instead of just a parcel.

fix(order-sync): Fix generating delivery update actions

---

src/coffee/connect/rest.coffee
src/spec/connect/rest.spec.coffee

Enable `limit` parameter to be overwritable from the outside classes.
Fixes: https://github.com/sphereio/sphere-node-sdk/issues/223

feat(rest): enable overwriting of page limit

---

src/coffee/services/product-projections.coffee
src/spec/client/services/product-projections.spec.coffee

This PR adds a possibility to turn on a priceSelection feature on productsProjection endpoint.
It is based on the same change in the new SDK - https://github.com/commercetools/nodejs/pull/170
Resolves #228 
- Tests

feat(productsProjection): Add price selection feature to productsProjection endpoint

---

src/coffee/services/base.coffee
src/coffee/services/product-projections.coffee
src/spec/client/services/product-projections.spec.coffee

Hello all .. I discovered that when we use `byQueryString` together with `process` we were not parsing correctly `limit` parameter so the pagination did not work properly. We were also deleting `queryString` from `@_params` object after first `@_get` call so the custom query was used only in the first API call.
In this PR I added a parsing of `limit` (and `perPage`) parameter and an update which preserves `queryString` attribute during all calls.
Fixes #239 
- Tests

fix(process): Fix process function when using byQueryString method

---

src/coffee/sync/utils/product.coffee
src/spec/sync/utils/product.spec.coffee

Resolves #236 - This PR adds a support for product.key and variant.key sync action.
- Tests

feat(productSync): Support key and variant key sync action

---

src/coffee/sync/utils/product.coffee
src/spec/sync/utils/product.spec.coffee

Update actions are done using `variantId` instead of `sku`.
- Tests

fix(productSync): Fix product sync update key and variantKey action

---

src/coffee/main.coffee

This PR exports `RepeaterTaskQueue` from SDK so it can be customized and used later for repeating API calls in the client.
Resolves https://github.com/sphereio/sphere-node-sdk/issues/247

Export repeaterTaskQueue from sdk

---

Gruntfile.coffee

Maps `grunt lint` to `grunt coffeelint` so both commands work
resolves #245

fix(lint): map grunt lint to coffeelint to enable both

---

src/coffee/sync/utils/category.coffee
src/spec/sync/category-sync.spec.coffee

PR adds `setKey` update action for category-sync
resolves #263

feat(sync): add setKey action for category-sync

---

src/coffee/sync/product-sync.coffee
src/coffee/sync/utils/product.coffee
src/spec/sync/product-sync-sku-match.spec.coffee
src/spec/sync/product-sync.spec.coffee
src/spec/sync/utils/product.spec.coffee

Fix how we match variants.
Originally, we were matching variants in a single loop by comparing id, sku or key.
Because we used id as a primary matching condition, there was happening, that we matched variants with the same ids but with different skus which later failed due to a duplicate slug error.
For example when syncing these two products:
```js
// existing product
{
masterVariant: {
id: 1,
sku: "sku1"
},
variants: [{
id: 2,
sku: "sku3"
}, {
id: 3,
sku: "sku2"
}]
}
// and new product
{
masterVariant: {
id: 1,
sku: "sku1"
},
variants: [{
id: 2,
sku: "sku2"
}, {
id: 3,
sku: "sku3"
}]
}
```
It would match variants using id and generate update actions:
```js
[{
action: "setSku",
variantId: 2,
sku: "sku2"
}, {
action: "setSku",
variantId: 3,
sku: "sku3"
}]
```
Which would fail because we …

fix(product-sync): fix matching variants

---

src/coffee/sync/utils/inventory.coffee
src/spec/sync/inventory-sync.spec.coffee

Fix update error in RestockableInDays
No update is shown when new RestockableInDays value is passed.
- Tests
closes #276

fix(inventory.coffee): fix error in restockable in days

---

src/coffee/sync/category-sync.coffee
src/coffee/sync/utils/category.coffee
src/spec/sync/category-sync.spec.coffee

This PR adds a possibility to sync category custom fields.
Resolves #280
- Tests

feat(category-sync): Add a possibility to sync category custom fields

---

src/coffee/sync/utils/category.coffee
src/spec/sync/category-sync.spec.coffee

This PR fixes how we sync boolean attributes.
Before this PR it generated remove action when I was changing `true` value to `false`.
**Lesson learned:** be more specific when dealing with `falsy` values.
- Tests

fix(categorySync): Sync properly boolean values in category sync

---

.travis.yml
README.md
package-lock.json
package.json
src/coffee/utils.coffee
src/spec/utils.spec.coffee

added method that returns the version of this SDK
This was necessary to remove dependency in sphere-node-utils to an unmaintained library that introduces vulnerabilities
- Tests
- [x ] Unit
- [x ] Integration
- [x ] Acceptance

feat: add method to get version number

---

src/coffee/main.coffee

need Utils in the public interface to use it from sphere-node-utils
Utils is exported, now it can be used externally. Because the new getVersion method is thought to be used externally. This is required to fix a vulnerability in sphere-node-utils that is spreading throughout the tools code base
- Tests
- [x ] Unit
- [ x] Integration
- [x ] Acceptance

fix(getVersion): add Utils to public interface of this module

---

src/coffee/sync/utils/product.coffee
src/spec/client/services/base.spec.coffee
src/spec/sync/product-sync-sku-match.spec.coffee
src/spec/sync/product-sync.spec.coffee
src/spec/sync/utils/product.spec.coffee

Pr is changing the product variant actions, now it's using SKU as the first option for variant update actions:
for example `setAttribute` action documentation explains it :
`variantId - Number or sku - String - Required`
We have lots of these kinds of errors: A staged variant with variantId '3' does not exist... I checked one of the product and it indeed doesn’t have that variant. I also checked the history of that product in master because I thought that the product could have before 3 variants and then one got removed. But it always has 2 variants. So it’s weird that we try to update with variant 3 when this variant never existed.
**It might not resolve the issue for us but could help with finding the reason.**
```
{
action: {
action: "setAttribute"        
name: "attributeName" …
```

feat(product-sync): on product variant actions, use SKU as the first option instead of variantId.
